name: CI

on:
  pull_request:
    paths:
      - carling/**
      - .github/workflows/ci.yml
      - poetry.lock

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install poetry tox
      - name: Test with tox
        run: poetry run tox -e py,black,flake8,isort
