name: CI

on:
  pull_request:
    paths:
      - carling/**
      - .github/workflows/ci.yml
      - poetry.lock
      - tox.ini

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==1.3.2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - name: Test with tox
        run: poetry run tox -e py,black,flake8,isort
